@startuml
title "Process_start function"
class  main  << (H,orchid) >>
class  process_start  << (H,orchid) >>



main --|> process_start :"set_prog_start &"
process start --|> main :"pid_t"



@enduml
